### ISSUE TITLE
Support both syntaxes for input fields

### ISSUE THREAD

**Issue by hugo187** [laposa/testflow#137]
**Description**

Can we allow the old syntax for input fields as well? Sometimes description isn't necessary (e.g. field name `email` is descriptive enough).

````yaml
 input:
      <name>: Some string
````

Keep supporting the new syntax as well.

````yaml
  input:
      <name>:
        description: what is this input field about
        value: some-example-value-that-could-be-copied-into-clipboard
````
